import { LegalShell, LegalSection, LegalList, legalMetadata } from '@/components/legal'
import { CONTACT_EMAIL, SUPPORT_EMAIL } from '@/lib/site'

export const metadata = legalMetadata(
  'Terms of Service',
  'The agreement between you and Cortex: accounts, acceptable use, AI outputs, Pro subscriptions, liability and governing law.',
  '/terms'
)

export default function TermsPage() {
  return (
    <LegalShell
      title="Terms of Service"
      updated="September 16, 2026"
      intro="These terms are the agreement between you and Cortex (&ldquo;the service&rdquo;), operated from Pakistan as part of the Scrutinies project. By creating an account or using the service you accept them. They are written to be readable — if anything is genuinely unclear, ask us at support@scrutinies.dev before relying on it."
    >
      <LegalSection n="01" title="Accounts">
        <p>
          You need an account with a verified email address to use the workspace. You are responsible
          for keeping your credentials confidential and for all activity under your account. You must
          be at least 13 years old (or the minimum digital-consent age where you live) and able to
          form a binding contract. One person, one account — shared team seats are not part of the
          current plans. Tell us immediately at {SUPPORT_EMAIL} if you suspect unauthorised access.
        </p>
      </LegalSection>

      <LegalSection n="02" title="Your content and your rights">
        <p>
          Your documents, notes, highlights, flashcards, plans, goals and everything else you put into
          Cortex remain yours. We claim no ownership over it. You grant us only the limited licence
          needed to run the service: storing, backing up, indexing it for your own search, rendering
          it to you, and processing task-scoped snippets through AI providers when you invoke an AI
          feature. We will never publish your content or use it to advertise.
        </p>
        <p>
          You confirm you have the rights to the material you upload. Scanning a book you borrowed or
          uploading PDFs you do not have the right to store is on you, not us, and we may remove
          content or suspend accounts where a rights-holder complains through a process we consider
          fair.
        </p>
      </LegalSection>

      <LegalSection n="03" title="Acceptable use">
        <LegalList
          items={[
            <span key="1">Do not use Cortex to store or distribute unlawful, hateful, harassing or infringing material.</span>,
            <span key="2">Do not probe, scan, overload or attempt to break authentication, rate limits or other users&apos; isolation.</span>,
            <span key="3">Do not resell access, scrape the service, or run automated accounts against the AI endpoints.</span>,
            <span key="4">Do not abuse the free plan (circumventing usage limits with extra accounts, scripted requests or payment fraud).</span>,
            <span key="5">Do not use the career and scholarship feeds as the basis of a competing aggregator; they are licensed data flows for your personal use.</span>,
          ]}
        />
        <p>
          We may suspend or terminate accounts that seriously or repeatedly breach these rules, with
          notice where practicable. Paid time remaining is handled under the refund policy.
        </p>
      </LegalSection>

      <LegalSection n="04" title="AI features and their limits">
        <p>
          The Copilot, document Q&amp;A, summaries, flashcards and mind maps are generated by
          third-party AI models. They are powerful but imperfect: they can misread context, invent a
          citation or get a number wrong. Treat AI output as a first draft from a fast assistant, not
          as professional, medical, legal or financial advice, and verify anything you act on. We
          continuously tune prompts and guardrails but do not warrant that outputs are accurate,
          complete or fit for any particular purpose.
        </p>
      </LegalSection>

      <LegalSection n="05" title="External information (feeds, jobs, scholarships)">
        <p>
          The news radar, papers feed, job listings and scholarship/exchange programmes are aggregated
          from third-party sources and refreshed automatically (including our daily feed sync).
          Deadlines, requirements and links can change or expire at the source without notice. We do
          our best to classify and dedupe honestly, but listings are provided for convenience only —
          always confirm details on the organisation&apos;s own page before applying or making plans.
        </p>
      </LegalSection>

      <LegalSection n="06" title="Pro subscriptions and billing">
        <p>
          The core workspace is free and unlimited for planning, notes, reading and career tracking.
          Pro adds higher or unlimited AI usage, larger storage and premium automations. When you
          subscribe:
        </p>
        <LegalList
          items={[
            <span key="1"><strong>International payments</strong> are processed by Lemon Squeezy, which acts as Merchant of Record and handles tax receipts; your bank statement will show their name.</span>,
            <span key="2"><strong>Pakistan-local payments</strong> (cards, wallets, bank transfer) are processed by Safepay.</span>,
            <span key="3">Subscriptions renew automatically at the billing interval you chose (monthly or annual) until cancelled — cancel anytime via the manage link in your receipt email or by writing to {SUPPORT_EMAIL}; access continues until the end of the paid period.</span>,
            <span key="4">Prices are shown before you pay, may include applicable taxes collected by the Merchant of Record, and can change with 30 days&apos; notice to existing subscribers.</span>,
            <span key="5">Students: discounted pricing is available — request it from {SUPPORT_EMAIL} with proof of enrolment, and keep the discount personal.</span>,
            <span key="6">Refunds follow the published <a className="underline underline-offset-2 hover:text-foreground" href="/refund">Refund Policy</a>.</span>,
          ]}
        />
      </LegalSection>

      <LegalSection n="07" title="Availability and changes">
        <p>
          We work hard to keep Cortex fast and available, but the service is provided as-is and
          as-available. There will be maintenance windows, occasional bugs, and — very rarely —
          outages beyond our control (upstream clouds, feed sources, AI providers). Features may
          evolve; if we retire something significant to your workflow we will give reasonable notice.
          Free-plan limits may be tuned to keep the service sustainable, with changes applied
          prospectively.
        </p>
      </LegalSection>

      <LegalSection n="08" title="Disclaimer and liability">
        <p>
          To the maximum extent permitted by law, Cortex is provided without warranties of any kind,
          express or implied, including fitness for a particular purpose. We are not liable for lost
          profits, missed deadlines, lost opportunities or other indirect damages arising from your
          use of the service or reliance on AI output or aggregated listings. Our total liability for
          any claim is limited to the amount you paid us in the 12 months before the claim (or, for
          free users, to the maximum permitted by law, which for practical purposes means no payment
          liability). Nothing in these terms limits liability that cannot lawfully be limited.
        </p>
      </LegalSection>

      <LegalSection n="09" title="Termination">
        <p>
          You can stop using Cortex and delete your account at any time; section 02 of the Privacy
          Policy explains what gets deleted and when. We can suspend or terminate the service to you
          for breach of these terms, payment failure or fraud, and can discontinue the service
          entirely with at least 30 days&apos; notice (giving active Pro subscribers a pro-rated
          refund for time paid but not received).
        </p>
      </LegalSection>

      <LegalSection n="10" title="Governing law and contact">
        <p>
          These terms are governed by the laws of Pakistan, and disputes will be resolved in the
          courts located there, except that either party may seek injunctive relief for intellectual
          property or security breaches in any competent jurisdiction. Before any formal step, we ask
          you to email {SUPPORT_EMAIL} — we commit to trying to resolve disputes in good faith
          within 30 days. Business and partnership enquiries: {CONTACT_EMAIL}.
        </p>
      </LegalSection>
    </LegalShell>
  )
}
